# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cebu/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),cebu)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,037b574d64b37311ddbf0e8ad75710232617860d)
$(call add-radio-file-sha1-checked,radio/modem.img,a58ea2d423440d8661a904c3b00c8c749a051e7e)
$(call add-radio-file-sha1-checked,radio/abl.img,8963306418380c97bbd3c74351bab37dc521c53e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4edc3b204b4c8aa509dc499a960cb339d83c8561)
$(call add-radio-file-sha1-checked,radio/dsp.img,a4d96325a5d65cc91374e29ba29d7bbf19f50bd7)
$(call add-radio-file-sha1-checked,radio/fsg.img,fedd3227c4f85d5bb45121c026eeaf6d8cdbf7fe)
$(call add-radio-file-sha1-checked,radio/hyp.img,568165e55d8d4d20f80d3c8222c3f4d1401480b1)
$(call add-radio-file-sha1-checked,radio/keymaster.img,365971f5b5a0f02953db8eb0a5b23f085866cc6c)
$(call add-radio-file-sha1-checked,radio/logo.img,d925f97a1cf9a10800fd541a80ea9ef530d44d59)
$(call add-radio-file-sha1-checked,radio/prov.img,dc388059ad7c10c301984f90f386a259da98f6a8)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0dcedfc3352a2f240ce84f5c11a5651ecdef366a)
$(call add-radio-file-sha1-checked,radio/rpm.img,961d685caa42bc10610013c80310e8a801ef2771)
$(call add-radio-file-sha1-checked,radio/storsec.img,92c8c20431dff8da8a9683747e12cff942356cfd)
$(call add-radio-file-sha1-checked,radio/tz.img,f150be2e0b0522eff00b727102cab008f70aa624)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,cef781dc975bbf7b10af25d04475421b680cf40e)
$(call add-radio-file-sha1-checked,radio/xbl.img,2928db3f0abcfbd2e4c2f30ecf5bccaee74e3d0a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a70237efe58976a82f64b9e8f6482c6afe304943)

endif
